### ISSUE TITLE
Avoid using github repos as dependencies

### ISSUE THREAD

**Issue by skeggse** [weo-edu/express-robots#7]
The `as-array` dependency of `express-robots` references another github repository directly (`git://github.com/weo-edu/as-array`). This causes problems on `npm@6.4.1` with `npm ci`:

```
└─┬ express-robots@0.1.6
  └── UNMET DEPENDENCY as-array@git://github.com/weo-edu/as-array.git#17a37ea02091a778c18c0e84465ddfc5dd321df7

npm ERR! missing: as-array@git://github.com/weo-edu/as-array.git, required by express-robots@0.1.6
```

Would you mind publishing `as-array` as a package, and updating the `package.json` here to reference it?

**Comment by joe-tohdjojo** [comment]
+1

**Comment by johnelliott** [comment]
#8
